---
language: ruby
cache: bundler
rvm:
- 2.5.8
- 2.6.6
addons:
  postgresql: '10'
install: bin/setup
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
after_script:
- bin/ci/after_script
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
