:api:
  :token_ttl: 10.minutes
  :authentication_timeout: 30.seconds
  :max_results_per_page: 1000
  :filter_parameters:
    - :conversion_host_ssh_private_key
    - :openstack_tls_ca_certs
    - :vmware_ssh_private_key
